### ISSUE TITLE
Stryker.NET GitHub Action

### ISSUE THREAD

**Issue by Stijn-Rutten** [stryker-mutator/stryker-net#1114]
**Describe the solution you'd like**
We should look at creating a GitHub action and publishing it to the market place. This would make Stryker.NET more accessible to users. Users can just search for the Stryker.NET action and copy the `yml` code. They only have to set arguments to their desired config.

**Additional context**
This would look something like this:
```
 - name: Run Stryker.NET
      uses: stryker-mutator/stryker-net@master
      with:
         reporters: ['dashboard', 'dots']
         config-file-path: <<path to config>>
         unit-test-project: <<path to test project>>
```
