### ISSUE TITLE
Run Stryker.NET against all projects in a solution

### ISSUE THREAD

**Issue by robertlarkins** [stryker-mutator/stryker-net#1118]
Not sure if this falls under feature request or issue, but when building and testing a solution using Azure DevOps I would like to easily run stryker against all projects in the solution. 

I'm running a dotnet core 3.1 solution and have installed dotnet-stryker as a local tool on the two test projects (as described [here](https://stryker-mutator.io/blog/2019-04-05/announcing-dotnet-framework-support#start-using-stryker-net)). I have the following but not sure how to make it project agnostic:

```yaml
- script: dotnet tool restore
  workingDirectory: 'tests/application/Company.Project.Application.Tests.Unit'
  displayName: 'Install dotnet tools for Stryker.CLI'

- script: dotnet tool run dotnet-stryker -tr dotnettest -r "['cleartext', 'html', 'progress']" --solution-path "../../../Company.Project.sln"
  workingDirectory: 'tests/application/Company.Project.Application.Tests.Unit' 
  displayName: 'Run Stryker on solution'

- task: PublishMutationReport@0
  inputs:
    reportPattern: '$(Build.SourcesDirectory)/tests/application/Company.Product.Application.Tests.Unit/StrykerOutput/*/reports/mutation-report.html'
```

Is it currently possible to target all projects, or is this a feature still being developed, as stated [here](https://stryker-mutator.io/blog/2020-05-15/azure-pipelines-integration#whats-next)?
