### ISSUE TITLE
Buildalyzer could not find sourcefiles (in CI pipeline)

### ISSUE THREAD

**Issue by patanric** [stryker-mutator/stryker-net#1990]
**Describe the bug**
Similar to #1899 I get the same Error:
```shell
[17:13:47 INF] Identifying project to mutate.
[17:13:54 INF] The project /home/vsts/work/1/s/Natzka.WebAPI.Web/Natzka.WebAPI.Web.csproj will be mutated.
[17:14:29 WRN] Buildalyzer could not find sourcefiles. This should not happen. Will fallback to filesystem scan. Please report an issue at github.
[17:14:29 INF] Analysis complete.
[17:14:29 INF] Building test project /home/vsts/work/1/s/Natzka.WebAPI.Web.Tests.Unit/Natzka.WebAPI.Web.Tests.Unit.csproj (1/1)
[17:14:53 INF] Time Elapsed 00:01:06.8390154
```

In an Azure DevOps pipeline I run the same task 3 times. Once for each project in the solution: Core, Infrastructure, Web.

<img src="https://user-images.githubusercontent.com/3979760/161440113-fdfbfd4d-4f10-4638-b6b6-4e7717b06fbe.png" width="400">

```yaml
  - task: Powershell@2
    displayName: 'Run Stryker: Core'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Natzka.WebAPI.Core.Tests.Unit'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker -p Natzka.WebAPI.Core.csproj'
```

And the only one that works is Core. Web and Infrastructure fail with the same error show above. Even If I change the sequence of the Stryker jobs, Infrastructure and Web fail.

On my PC everything works just fine.

As mentioned the Core project just works. From the same pipeline run as above:
```shell
[17:09:26 INF] Identifying project to mutate.
[17:09:30 INF] The project /home/vsts/work/1/s/Natzka.WebAPI.Core/Natzka.WebAPI.Core.csproj will be mutated.
[17:09:32 INF] Analysis complete.
[17:09:32 INF] Building test project /home/vsts/work/1/s/Natzka.WebAPI.Core.Tests.Unit/Natzka.WebAPI.Core.Tests.Unit.csproj (1/1)
[17:09:54 INF] Total number of tests found: 175.
[17:09:54 INF] Initial testrun started.
```

**Expected behavior**
Should find the source files and run Stryker.

**Environment**
 - OS: Linux agent in Azure DevOps pipeline
 - Type of project: core
 - Framework Version: .NET 6
 - Stryker Version: 1.5.0

**Additional context**
This is how the pipeline is configured:

```yaml
schedules:
  - cron: "0 5 * * *"
    displayName: Daily morning build
    branches:
      include:
        - feature/2961_stryker_mutator_daily_build

pool:
  vmImage: 'ubuntu-20.04'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install dotnet-stryker --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources --tool-path $(Agent.BuildDirectory)/tools'

  - task: Powershell@2
    displayName: 'Run Stryker: Core'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Natzka.WebAPI.Core.Tests.Unit'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker -p Natzka.WebAPI.Core.csproj'

  - task: Powershell@2
    displayName: 'Run Stryker: Web'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Natzka.WebAPI.Web.Tests.Unit'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker -p Natzka.WebAPI.Web.csproj'

  - task: Powershell@2
    displayName: 'Run Stryker: Infrastructure'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Natzka.WebAPI.Infrastructure.Tests.Unit'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker -p Natzka.WebAPI.Infrastructure.csproj'

  - task: PublishMutationReport@1
    condition: succeededOrFailed()
    displayName: 'Publish Stryker Mutator Report'
    inputs:
      reportPattern: '**/mutation-report.html'
```

**Comment by rouke-broersma** [comment]
Could you share Natzka.WebAPI.Web.csproj with us? Any confidential names can be obfuscated or entirely removed. Most of the things relevant to us are probably standard msbuild elements like sdk, dotnet version, language version etc. Anything that isn't standard like custom msbuild targets could also be relevant but if they cannot be shared a description of them can also be useful. Without this we have no way to reproduce this issue unless we stumble upon it by accident ourselves.

**Comment by patanric** [comment]
Alright, it turned out that the problem was the Nuget restore step in dotnet-stryker. So, to fix the problem, I added following task before running anything other task:
```
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      vstsFeed: '$(vstsFeedId)'
```

I still need to `--ignore-failed-sources` in the `install dotnet-stryker` step. Just like this:
`install dotnet-stryker --ignore-failed-sources --tool-path $(Agent.BuildDirectory)/tools`

Thank you for your help!
