### ISSUE TITLE
YAML configuration for stryker

### ISSUE THREAD

**Issue by chripf** [stryker-mutator/stryker-net#2100]
When creating a stryker-config, it would be helpful to add comments e.g. to explain an "ignore-methods" entry. `json` however does not allow comments.

Having the option to use a `stryker-config.yaml` configuration will allow a leaner structure of the configuration file (a matter of taste, admittedly) and the option to  add comments while staying valid.
Example:

```
---
stryker-config:
  ignore-methods:
  - "*Log" # ignore log mutations
  - Console.Write* # do not care about command line output
  - "*Exception.ctor"
  - ApiError.ctor
  project: My.Test.Project
```
