### ISSUE TITLE
'Unhandled exception. System.MissingMethodException' on .NET7 project with preview language

### ISSUE THREAD

**Issue by Stijnwingens** [stryker-mutator/stryker-net#2797]
**Describe the bug**
Even though I'm using the language-version: Preview option, the Stryker.NET execution fails (System.MissingMethodException). The error message suggests that the language version is not read (or used by me) correctly?

**Logs**
[logs.zip](https://github.com/stryker-mutator/stryker-net/files/13658714/logs.zip)

Logs found in attachments.

**Expected behavior**
No exception.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio Solution
 - .NET7 (preview language version)
 - Stryker Version 3.12.0

**Additional context**
First time using Stryker.NET. Using the following conf file (stryker-config.yml):
```yml
  stryker-config:
    language-version: Preview
    target-framework: net7.0
    
    mutation-level: Complete
    reporter: html
```
run with `dotnet stryker -f stryker-config.yml`
